
title: Ilya's Site
# email: your-email@example.com
description: >-
  my site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

lang: ja
timezone: Asia/Jakarta
encoding: utf-8
markdown: kramdown

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# theme: rouge

sass:
  style: compressed
  # sass_dir: _sass

collections:
  assets:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/posts/:year/:month/:day/:title/" #:output_ext"
  -
    scope:
      path: "_pages"
      # type: "pages"
    values:
      layout: "page"
      permalink: "/pages/:title/" #:output_ext"

